# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-6.7"
  #config.vm.box = "chef/ubuntu-14.10"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box 
  end

  if private_network_ip = ENV["VAGRANT_PRIVATE_NETWORK_IP"]
    config.vm.network "private_network", ip: private_network_ip
  end

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = ENV["VAGRANT_MEMORY"]
  end

  # fix key path to ~/.vagrant/insecure_private_key
  config.ssh.insert_key = false
end
