# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box 
  end

  config.vm.define :centos do |host|
    host.vm.box = "bento/centos-6.7"
    host.vm.hostname = "centos.example"
    if private_network_ip = ENV["VAGRANT_CENTOS"]
      host.vm.network "private_network", ip: private_network_ip
    end
  end

  config.vm.define :ubuntu do |host|
    host.vm.box = "chef/ubuntu-14.10"
    host.vm.hostname = "ubuntu.example"
    if private_network_ip = ENV["VAGRANT_UBUNTU"]
      host.vm.network "private_network", ip: private_network_ip
    end
  end

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = ENV["VAGRANT_MEMORY"]
  end

  # fix key path to ~/.vagrant/insecure_private_key
  config.ssh.insert_key = false
end
